const arr = [90, 102, 1231, 3112, 801, 812];
var a = arr[0];
var b = arr[1];
var c = arr[2];
var d = arr[3];
var e = arr[4];
var f = arr[5];
//console.log(a, b , c , d , e ,f);
console.log(a);
 console.log(b);
 console.log(c);
 console.log(d);
 console.log(e);
 console.log(f);